// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sndonowgrtwbqumnagiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZG9ub3dncnR3YnF1bW5hZ2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTE5MTYsImV4cCI6MjA2MjgyNzkxNn0.lZ6vYeALa1Qr2j1YZDh-ZHC4Hfh17V2LmMfzrjYyJsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);